version: '2'

services:
   honeycomb:
      container_name: cucpserver2
      image: gn:latest
      ports:
        - "2853:2831"
      hostname: honeycomb
      command: honeycomb
      volumes:
        - ./config:/opt/app/honeycomb/config
      environment:
        - enodebsimIp=10.31.4.14
        - enodebsimPort=2853
      restart: on-failure
