version: '2'

services:
   honeycomb:
      container_name: "1111"
      image: gn:latest
      ports:
        - "2854:2831"
      hostname: honeycomb
      command: honeycomb
      volumes:
        - ./config:/opt/app/honeycomb/config
      environment:
        - enodebsimIp=10.31.4.14
        - enodebsimPort=2854
      restart: on-failure
