version: '2'

services:
   honeycomb:
      container_name: "22"
      image: gn:latest
      ports:
        - "2851:2831"
      hostname: honeycomb
      command: honeycomb
      volumes:
        - ./config:/opt/app/honeycomb/config
      environment:
        - enodebsimIp=10.31.4.14
        - enodebsimPort=2851
      restart: on-failure
